name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - src/**

jobs:

  build:

    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file src/Dockerfile --tag my-image-name:$(date +%s)
